### ISSUE TITLE
Override default "canvasloader-container"

### ISSUE THREAD

**Issue by jonathan-huteau** [Troopers/AjaxBundle#36]
Hi,

How could I change the loader shown on ajax request ?

I saw this part of code 
```javascript
if (loader == undefined) {
    var loader = '<div id="canvasloader-container" style="display: none;"><img src="/bundles/troopersajax/img/three-dots.svg" style="width: 80%; padding-top: 15px;"/></div><div id="canvasloader-container--overlay" style="display: none;"></div>';
}
```
(https://github.com/Troopers/AjaxBundle/blob/master/Resources/public/js/ajax.js#L3)

I tried to set `loader = $('#overlay')` before include `ajax.js` script but it's always same as `undefined`

**Comment by lenybernard** [comment]
Hi Jonathan,

That's weird, that should work.
I'll take a look and I'll come back to you soon.

**Comment by jonathan-huteau** [comment]
Thanks @lenybernard,
I can provide some source code if it can help
